name: Request Artwork
description: Request a new artwork for a game or software.
title: "!!! DON'T CHANGE !!!"
labels: [request]
body:
- type: dropdown
  id: artwork_type
  attributes:
    label: Artwork Type
    options:
      - Game
      - Software
    default: 0
  validations:
    required: true
- type: input
  id: app_id
  attributes:
    label: App ID
    description: The App ID of the game or software. - You can find it on https://steamdb.info or https://store.steampowered.com
    placeholder: "570"
  validations:
    required: true
- type: input
  id: image
  attributes:
    label: Image URL
    description: Only SteamGridDB links are allowed. Allowed filters are dimension "3840x1240", style "Alternate", file type "PNG" and "JPEG/JPG", tag "Untagged" and "Static" images. - You can find it on https://steamgriddb.com
    placeholder: "https://www.steamgriddb.com/hero/11836"
  validations:
    required: true